apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-app.fullname" . }}-config
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
data:
  config.json: |-
{{ .Files.Get "files/config.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-app.fullname" . }}-env
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.environment | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  APP_NAME: {{ .Values.config.appName | quote }}
